### ISSUE TITLE
Error in GaMPEN Getting Started Docs

### ISSUE THREAD

**Issue by AndrewC13Y** [aritraghsh09/GaMPEN#10]
In the GaMPEN Getting Started documentation (https://gampen.readthedocs.io/en/latest/Getting_Started.html), it is suggested to run the trainer with the following code:

`python ggt/train/train.py \
  --experiment_name='demo' \
  --data_dir='./../hsc/' \
  --split_slug='balanced-dev2' \
  --batch_size=16 \
  --epochs=2 \
  --lr=5e-7 \
  --momentum=0.99 \
  --crop \
  --cutout_size=239 \
  --target_metrics='custom_logit_bt,log_R_e,log_total_flux' \
  --repeat_dims \
  --no-nesterov \
  --label_scaling='std' \
  --dropout_rate=0.0004 \
  --loss='aleatoric_cov' \
  --weight_decay=0.0001 \
  --parallel`

Upon investigation of the target_metrics in the info.csv file within the hsc directory, the correct target_metrics should be `custom_logit_bt,ln_R_e_asec,ln_total_flux_adus` rather than `custom_logit_bt,log_R_e,log_total_flux`.

**Comment by aritraghsh09** [comment]
Fixed now! 

https://github.com/aritraghsh09/GaMPEN/commit/3ea8b7daa39a8dcc8a02823509c945d8f9b92bb4
