### ISSUE TITLE
Autocropping tutorial 

### ISSUE THREAD

**Issue by iam37** [aritraghsh09/GaMPEN#6]
Trying to download the packages necessary through r-requirements.txt for autocropping.ipynb in Google Colab runs into issues downloading PANDAS on my machine. When the programs attempts to download PANDAS, it pauses for several minutes and then throws the following error: 

`error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing build dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by aritraghsh09** [comment]
This was being triggered by a backend update of Colab to a more recent Python version. 

I have now added a miniconda installation step to the tutorial which allows users to choose their own Python version. 

https://github.com/aritraghsh09/GaMPEN/commit/769cdb64a76c9a98a6307a25d4cb6af2aaf1b2ed
